{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:7Amplify12GraphQLErrorV","text":"GraphQLError","kind":"typeIdentifier","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLError"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLResponseError"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"An error response. The associated value will be an array of GraphQLError objects that contain service-specific"},{"type":"text","text":" "},{"type":"text","text":"error messages. https:\/\/graphql.github.io\/graphql-spec\/June2018\/#sec-Errors"}],"metadata":{"title":"GraphQLResponseError.error(_:)","roleHeading":"Case","role":"symbol","externalID":"s:7Amplify20GraphQLResponseErrorO5erroryACyxGSayAA0B7QLErrorVGcAEmSeRzlF","symbolKind":"case","modules":[{"name":"Amplify"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"([","kind":"text"},{"text":"GraphQLError","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify12GraphQLErrorV"},{"text":"])","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/graphqlresponseerror\/error(_:)"]}],"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLResponseError\/error(_:)","interfaceLanguage":"swift"},"references":{"doc://amplify-swift.Amplify/documentation/Amplify/GraphQLResponseError":{"title":"GraphQLResponseError","kind":"symbol","abstract":[{"type":"text","text":"An error response from a GraphQL API"}],"url":"\/documentation\/amplify\/graphqlresponseerror","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GraphQLResponseError","kind":"identifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLResponseError","navigatorTitle":[{"kind":"identifier","text":"GraphQLResponseError"}],"type":"topic"},"doc://amplify-swift.Amplify/documentation/Amplify/GraphQLResponseError/error(_:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"An error response. The associated value will be an array of GraphQLError objects that contain service-specific","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"error messages. https:\/\/graphql.github.io\/graphql-spec\/June2018\/#sec-Errors"}],"type":"topic","title":"GraphQLResponseError.error(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:7Amplify12GraphQLErrorV","text":"GraphQLError","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/amplify\/graphqlresponseerror\/error(_:)","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLResponseError\/error(_:)"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/GraphQLError":{"navigatorTitle":[{"text":"GraphQLError","kind":"identifier"}],"title":"GraphQLError","abstract":[{"type":"text","text":"The error format according to https:\/\/graphql.github.io\/graphql-spec\/June2018\/#sec-Errors"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GraphQLError"}],"url":"\/documentation\/amplify\/graphqlerror","role":"symbol"}}}