{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"]]},"metadata":{"role":"symbol","roleHeading":"Case","title":"AuthError.service(_:_:_:)","externalID":"s:7Amplify9AuthErrorO7serviceyACSS_SSs0C0_pSgtcACmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"service"},{"kind":"text","text":"("},{"text":"ErrorDescription","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify16ErrorDescriptiona"},{"kind":"text","text":", "},{"text":"RecoverySuggestion","preciseIdentifier":"s:7Amplify18RecoverySuggestiona","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"modules":[{"name":"Amplify"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/service(_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"service","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/ErrorDescription","preciseIdentifier":"s:7Amplify16ErrorDescriptiona","kind":"typeIdentifier","text":"ErrorDescription"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","preciseIdentifier":"s:7Amplify18RecoverySuggestiona","text":"RecoverySuggestion"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Caused by some error in the underlying service. Check the associated error for more details."}],"variants":[{"paths":["\/documentation\/amplify\/autherror\/service(_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/RecoverySuggestion":{"url":"\/documentation\/amplify\/recoverysuggestion","title":"RecoverySuggestion","type":"topic","abstract":[{"type":"text","text":"See: "},{"identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"reference","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecoverySuggestion","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RecoverySuggestion","kind":"identifier"}]},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError":{"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"kind":"symbol","role":"symbol","url":"\/documentation\/amplify\/autherror","title":"AuthError","type":"topic","abstract":[{"type":"text","text":"Amplify error raised in the Auth category."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"},"x-source-tag://AmplifyError.recoverySuggestion":{"title":"AmplifyError.recoverySuggestion","identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","titleInlineContent":[{"text":"AmplifyError.recoverySuggestion","type":"text"}],"url":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"link"},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/service(_:_:_:)":{"role":"symbol","title":"AuthError.service(_:_:_:)","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/service(_:_:_:)","abstract":[{"text":"Caused by some error in the underlying service. Check the associated error for more details.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"service"},{"kind":"text","text":"("},{"text":"ErrorDescription","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify16ErrorDescriptiona"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7Amplify18RecoverySuggestiona","text":"RecoverySuggestion","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"url":"\/documentation\/amplify\/autherror\/service(_:_:_:)"},"x-source-tag://AmplifyError.errorDescription":{"type":"link","identifier":"x-source-tag:\/\/AmplifyError.errorDescription","titleInlineContent":[{"text":"AmplifyError.errorDescription","type":"text"}],"url":"x-source-tag:\/\/AmplifyError.errorDescription","title":"AmplifyError.errorDescription"},"doc://amplify-swift.Amplify/documentation/Amplify/ErrorDescription":{"url":"\/documentation\/amplify\/errordescription","title":"ErrorDescription","type":"topic","abstract":[{"type":"text","text":"See: "},{"type":"reference","identifier":"x-source-tag:\/\/AmplifyError.errorDescription","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/ErrorDescription","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorDescription"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorDescription"}]}}}