{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/amplify\/autherror\/underlyingerror"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"The underlying error that caused the error condition","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/underlyingError"},"metadata":{"extendedModule":"Amplify","externalID":"s:7Amplify9AuthErrorO010underlyingC0s0C0_pSgvp","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"underlyingError","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"underlyingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"Amplify"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlyingError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/AmplifyError-Implementations"]]},"references":{"doc://amplify-swift.Amplify/documentation/Amplify/AuthError":{"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"kind":"symbol","role":"symbol","url":"\/documentation\/amplify\/autherror","title":"AuthError","type":"topic","abstract":[{"type":"text","text":"Amplify error raised in the Auth category."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/AmplifyError-Implementations":{"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/AmplifyError-Implementations","abstract":[],"title":"AmplifyError Implementations","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/amplify\/autherror\/amplifyerror-implementations"},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/underlyingError":{"url":"\/documentation\/amplify\/autherror\/underlyingerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"underlyingError"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/underlyingError","abstract":[{"type":"text","text":"The underlying error that caused the error condition"}],"role":"symbol","title":"underlyingError","type":"topic","kind":"symbol"}}}