{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errors","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:7Amplify12GraphQLErrorV","text":"GraphQLError","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLError","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/DataStoreSyncConflict\/errors","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/datastoresyncconflict\/errors"]}],"metadata":{"modules":[{"name":"Amplify"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errors"},{"text":": [","kind":"text"},{"text":"GraphQLError","preciseIdentifier":"s:7Amplify12GraphQLErrorV","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"errors","externalID":"s:7Amplify21DataStoreSyncConflictV6errorsSayAA12GraphQLErrorVGSgvp","roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/DataStoreSyncConflict"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://amplify-swift.Amplify/documentation/Amplify/DataStoreSyncConflict":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataStoreSyncConflict","kind":"identifier"}],"title":"DataStoreSyncConflict","kind":"symbol","type":"topic","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/DataStoreSyncConflict","url":"\/documentation\/amplify\/datastoresyncconflict","abstract":[{"type":"text","text":"Information about a conflict that occurred attempting to sync a local model with a remote model"}],"navigatorTitle":[{"text":"DataStoreSyncConflict","kind":"identifier"}],"role":"symbol"},"doc://amplify-swift.Amplify/documentation/Amplify/GraphQLError":{"navigatorTitle":[{"text":"GraphQLError","kind":"identifier"}],"title":"GraphQLError","abstract":[{"type":"text","text":"The error format according to https:\/\/graphql.github.io\/graphql-spec\/June2018\/#sec-Errors"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/GraphQLError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GraphQLError"}],"url":"\/documentation\/amplify\/graphqlerror","role":"symbol"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/DataStoreSyncConflict/errors":{"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/DataStoreSyncConflict\/errors","url":"\/documentation\/amplify\/datastoresyncconflict\/errors","title":"errors","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errors"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GraphQLError","preciseIdentifier":"s:7Amplify12GraphQLErrorV"},{"kind":"text","text":"]?"}],"abstract":[],"role":"symbol","kind":"symbol"}}}